In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score

## Part 1: Import the Housing data and do feature transformations

In [4]:
df= pd.read_csv('house_price_full.csv')
df.head()

   bedrooms  sqft_living    price
0         3         1340   313000
1         5         3650  2384000
2         3         1930   342000
3         3         2000   420000
4         4         1940   550000

In [6]:
X = df.copy()
# Remove target
Y = X.pop('price')

# perform a scaler transform of the input data
scaler = StandardScaler()
X = scaler.fit_transform(X)

# perform log transformation of target variable (For Sandeep: Is this needed?)
Y = np.log(Y)

In [8]:
df_scaled = pd.DataFrame(X)
df_scaled

            0         1
0   -0.433198 -0.753258
1    1.675735  1.457330
2   -0.433198 -0.188649
3   -0.433198 -0.121661
4    0.621269 -0.179079
..        ...       ...
494  0.621269  0.873582
495  1.675735  2.299459
496 -0.433198 -0.724549
497 -0.433198 -0.179079
498 -0.433198 -1.040347

[499 rows x 2 columns]

In [10]:
Y

0      12.653958
1      14.684290
2      12.742566
3      12.948010
4      13.217674
         ...
494    13.380102
495    13.764217
496    12.128111
497    12.721886
498    12.254863
Name: price, Length: 499, dtype: float64

## Part 2: Create Model Using `keras`

![](multiple_neurons.png)

In [13]:
from tensorflow import keras

In [15]:
model = keras.Sequential(
    [
        keras.layers.Dense(
            2, activation="sigmoid", input_shape=(X.shape[-1],)
        ),
        keras.layers.Dense(1, activation="linear")
    ]
)
model.summary()

C:\Users\ATANU\AppData\Roaming\Python\Python311\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 2)              │             6 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 1)              │             3 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 9 (36.00 B)

 Trainable params: 9 (36.00 B)

 Non-trainable params: 0 (0.00 B)

```python
def random_init_params():
    w1 = tf.Variable(tf.random.uniform((2, 2)))
    b1 = tf.Variable(tf.random.uniform((1, 2)))
    w2 = tf.Variable(tf.random.uniform((2, 1)))
    b2 = tf.Variable(tf.random.uniform((1, 1)))
    return w1,b1,w2,b2


def forward_prop(x, w1, b1, w2, b2):
    z1 = tf.matmul(x,w1) + b1
    h1 = tf.math.sigmoid(z1)
    z2 = tf.matmul(h1,w2) + b2
    h2 = z2
    return h2
```

In [18]:
model.compile(
    optimizer=keras.optimizers.SGD(), loss="mean_squared_error"
)

```python
def train(x, y, w1, b1, w2, b2):
    y_true = y
    with tf.GradientTape() as g:
        y_pred = forward_prop(x, w1, b1, w2, b2)

        # loss
        loss = 0.5*(y_true - y_pred)** 2
    
    #Gradient calculation  
    print("**************************************************")
    print("GRADIENTS")
    print("**************************************************")
    gw1, gb1, gw2, gb2 = g.gradient(loss, [w1, b1, w2, b2])
    print(" the gradient for 1st layer weights are:\n",gw1.numpy())
    print("--------------------------------------------------")
    print(" the gradient for 2nd layer weights are:\n",gw2.numpy())
    print("--------------------------------------------------")
    print(" the gradient for 1st layer bias are:\n",gb1.numpy())
    print("--------------------------------------------------")
    print(" the gradient for 2nd layer bias are:\n",gb2.numpy())
    print("--------------------------------------------------")

    # Gradient descent:
    lr=0.2
    w1.assign_sub(lr*gw1)
    b1.assign_sub(lr*gb1) 
    w2.assign_sub(lr*gw2)
    b2.assign_sub(lr*gb2)
    print("**************************************************")
    print("NEW UPDATES")
    print("**************************************************")
    print(" the updated 1st layer weights are:\n",w1.numpy())
    print("--------------------------------------------------")
    print(" the updated 2nd layer weights are:\n",w2.numpy())
    print("--------------------------------------------------")
    print(" the updated 1st layer bias are:\n",b1.numpy())
    print("--------------------------------------------------")
    print(" the updated 2nd layer bias are:\n",b2.numpy())


    return w1, b1, w2, b2,loss

```

In [21]:
model.fit(X,Y.values,epochs=10,batch_size=32)

Epoch 1/10
16/16 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 127.9233
Epoch 2/10
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 35.1800
Epoch 3/10
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 7.7065
Epoch 4/10
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 2.1109
Epoch 5/10
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.9289
Epoch 6/10
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.6337
Epoch 7/10
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.4456
Epoch 8/10
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.3547
Epoch 9/10
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.2776
Epoch 10/10
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.2454

In [23]:
model.predict(X)[:,0]

16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step

array([12.945429 , 13.075906 , 13.2001915, 13.22177  , 13.049098 ,
       12.805338 , 13.099473 , 13.213704 , 13.321167 , 12.874598 ,
       13.121131 , 13.232193 , 13.302748 , 12.792965 , 13.069603 ,
       12.86357  , 13.061284 , 13.241493 , 12.96183  , 12.85115  ,
       13.283856 , 12.838425 , 13.136829 , 13.21587  , 12.913349 ,
       13.247146 , 13.30855  , 13.124418 , 13.06216  , 13.346735 ,
       12.894315 , 13.227842 , 13.006311 , 13.224539 , 13.23797  ,
       13.389868 , 12.745096 , 13.173467 , 13.209641 , 13.314114 ,
       13.065818 , 12.85419  , 12.783102 , 13.144451 , 13.022267 ,
       12.838544 , 13.212724 , 13.2001915, 12.905603 , 13.244686 ,
       13.213704 , 13.376974 , 13.359734 , 13.155607 , 12.958227 ,
       13.0423355, 13.121933 , 13.075449 , 12.934274 , 13.229367 ,
       13.244686 , 13.35645  , 13.21587  , 13.3385   , 13.232193 ,
       12.819926 , 13.09643  , 12.738066 , 13.484971 , 13.274723 ,
       13.190001 , 13.372619 , 13.143194 , 13.190432 , 12.939873 ,
       13.0564   , 13.116867 , 13.21587  , 13.103643 , 13.330989 ,
       13.065375 , 13.2353115, 13.467592 , 13.155607 , 13.15602  ,
       13.385388 , 12.980422 , 13.018623 , 13.129991 , 13.016423 ,
       13.082243 , 13.265119 , 12.893982 , 13.306643 , 13.056709 ,
       13.054039 , 13.108955 , 13.07954  , 12.983086 , 13.052702 ,
       13.243332 , 13.224719 , 12.939873 , 13.162044 , 12.838296 ,
       13.231518 , 13.0896015, 13.184648 , 12.775596 , 12.716737 ,
       12.805696 , 13.149739 , 12.765892 , 13.028587 , 13.071638 ,
       12.4430275, 13.281616 , 12.752792 , 13.082457 , 13.104819 ,
       13.058971 , 13.003649 , 11.679328 , 13.183752 , 13.183752 ,
       12.983086 , 12.85419  , 12.980422 , 13.196973 , 13.231518 ,
       13.389868 , 13.0520935, 12.912432 , 13.41099  , 13.28297  ,
       13.147588 , 13.155607 , 13.071638 , 13.151925 , 13.175119 ,
       13.203375 , 12.992602 , 13.244162 , 13.176153 , 13.061739 ,
       13.08355  , 12.982039 , 13.384186 , 13.00438  , 13.212713 ,
       13.176879 , 12.833081 , 12.955518 , 12.950939 , 13.111674 ,
       13.02353  , 13.22177  , 12.910174 , 12.681828 , 12.902847 ,
       13.065818 , 13.100901 , 12.753559 , 13.087883 , 13.244463 ,
       13.0319195, 12.874598 , 12.819926 , 12.765892 , 12.899735 ,
       12.909073 , 13.145406 , 13.22366  , 13.09643  , 13.092176 ,
       13.173467 , 13.068524 , 12.983086 , 12.864481 , 13.32619  ,
       12.738066 , 13.033821 , 13.154163 , 12.965855 , 13.176879 ,
       13.241163 , 13.086693 , 13.173467 , 13.013817 , 13.232796 ,
       12.988291 , 13.033217 , 13.2576   , 13.242533 , 13.087883 ,
       13.151925 , 13.068524 , 13.138683 , 13.238373 , 12.928629 ,
       13.224379 , 13.231714 , 13.077407 , 13.069603 , 13.38067  ,
       13.241461 , 13.2437105, 13.210285 , 12.881858 , 13.216921 ,
       13.244377 , 12.806221 , 12.822245 , 13.190432 , 12.841455 ,
       13.113052 , 12.988291 , 13.002029 , 13.215773 , 12.998625 ,
       13.274723 , 12.579542 , 13.018623 , 13.068098 , 13.357566 ,
       13.240249 , 12.905603 , 13.00438  , 13.238825 , 12.84487  ,
       12.915555 , 12.723869 , 13.173334 , 13.171756 , 12.893822 ,
       13.047437 , 13.074764 , 12.806221 , 13.169967 , 13.335567 ,
       13.35645  , 12.360718 , 13.169682 , 12.966463 , 13.241731 ,
       13.140658 , 13.108955 , 13.195444 , 13.356012 , 13.010083 ,
       12.977837 , 13.180359 , 12.425076 , 12.91679  , 13.360786 ,
       12.738066 , 13.065818 , 13.200145 , 13.196973 , 13.306643 ,
       13.093372 , 13.186876 , 13.389868 , 13.32619  , 12.896803 ,
       12.760441 , 13.005703 , 13.144451 , 13.099473 , 13.209641 ,
       13.24468  , 13.468971 , 13.04224  , 13.149739 , 12.936199 ,
       13.206659 , 13.0319195, 13.272366 , 13.230518 , 13.290405 ,
       13.079178 , 12.7138405, 13.233436 , 13.087883 , 12.906867 ,
       13.380098 , 13.203375 , 12.983086 , 12.759006 , 12.760441 ,
       12.827149 , 12.722298 , 13.119415 , 13.074764 , 13.028395 ,
       12.945429 , 13.17693  , 13.3385   , 12.91679  , 12.967209 ,
       13.092176 , 13.07536  , 13.10903  , 13.140658 , 13.100644 ,
       13.166431 , 13.126873 , 12.859357 , 12.899735 , 13.028588 ,
       13.223021 , 12.986535 , 13.207401 , 13.003744 , 13.077417 ,
       12.760441 , 13.19103  , 13.247146 , 13.081765 , 12.970625 ,
       13.104819 , 13.193024 , 13.077407 , 12.893822 , 13.074718 ,
       13.207891 , 12.876398 , 13.209641 , 12.681828 , 13.104665 ,
       13.316999 , 13.106353 , 13.0025015, 13.406586 , 13.113052 ,
       13.203375 , 13.151862 , 13.086693 , 13.244034 , 13.136382 ,
       12.972545 , 12.929883 , 13.02353  , 13.181995 , 13.009532 ,
       13.283856 , 13.196973 , 13.187109 , 13.136382 , 13.0564   ,
       12.862562 , 13.244644 , 13.068524 , 12.903511 , 13.013817 ,
       13.215773 , 12.90823  , 13.033821 , 13.143194 , 13.321167 ,
       13.377635 , 13.143194 , 13.033217 , 12.694909 , 12.857384 ,
       12.928629 , 13.060266 , 13.136829 , 12.934274 , 13.178611 ,
       12.887863 , 12.899735 , 12.884867 , 13.228226 , 13.047437 ,
       13.195444 , 13.008683 , 12.972545 , 13.351769 , 13.070312 ,
       13.0389   , 13.226181 , 12.983086 , 12.961813 , 12.790561 ,
       13.298744 , 12.903511 , 12.876398 , 13.195629 , 13.092176 ,
       13.228832 , 13.221843 , 12.97883  , 12.827693 , 13.173467 ,
       12.862562 , 13.329414 , 13.23226  , 13.200145 , 12.972545 ,
       13.138683 , 13.180317 , 12.752792 , 12.936199 , 13.382279 ,
       12.681828 , 12.972545 , 13.001116 , 13.30715  , 13.249806 ,
       12.772731 , 13.028395 , 13.058971 , 12.983086 , 13.233834 ,
       13.121933 , 13.196973 , 12.838544 , 12.974194 , 13.068524 ,
       13.115064 , 13.081778 , 13.226232 , 12.986535 , 13.241163 ,
       12.988291 , 13.173334 , 13.045735 , 13.100644 , 12.977837 ,
       13.207891 , 13.068524 , 13.106353 , 12.952036 , 13.136829 ,
       12.984791 , 13.134931 , 13.049098 , 12.983086 , 12.956407 ,
       12.875808 , 13.225396 , 13.230593 , 13.153955 , 13.387274 ,
       12.848979 , 13.239674 , 12.752073 , 13.045735 , 13.148207 ,
       13.22177  , 13.113052 , 12.910714 , 12.92294  , 13.167813 ,
       12.986535 , 13.149739 , 13.21587  , 13.226232 , 12.903511 ,
       12.945429 , 13.241177 , 12.571443 , 12.72957  , 13.078316 ,
       13.2576   , 13.188451 , 13.049098 , 12.950939 , 13.114286 ,
       12.96183  , 13.043196 , 13.225396 , 13.224719 , 13.244673 ,
       13.033821 , 13.125113 , 12.900256 , 13.056709 , 13.341338 ,
       13.143447 , 13.028067 , 13.075906 , 13.267564 , 13.1915245,
       12.827149 , 13.235844 , 13.103643 , 13.243195 , 13.016849 ,
       13.274723 , 12.970625 , 13.377635 , 12.723869 , 13.238825 ,
       12.999656 , 12.96183  , 13.203375 , 12.759006 ], dtype=float32)